### ISSUE TITLE
For some reason this stopped working for asciidoctor-deck.js. When it parse just fine if I do an HTML

### ISSUE THREAD

**Issue by dhinojosa** [asciidoctor/asciidoctor-deck.js#3]
Sorry, @mojavelinux my mistake, put the issue here. I'll remove it from epub3.

± % asciidoctor -T ../asciidoctor-deck.js/templates/haml what_the_hell_are_math_nerds_talking_about_1.asc                                   !10216
asciidoctor: FAILED: /home/danno/documents/presentations/what_the_hell_are_math_nerds_talking_about/what_the_hell_are_math_nerds_talking_about_1.asc: Failed to parse source, Could not find a converter to handle transform: inline_quoted (RuntimeError)
  Use --trace for backtrace

**Comment by mojavelinux** [comment]
Can you verify that there is an inline_quoted.html.haml file in the templates folder?

Also, make sure that the backend is not set in the documents. When using templates, you shouldn't set the backend. Just point to the templates folder. That way, it falls back to the built-in HTML templates if, for some reason, any node is missing a template file.

**Comment by dhinojosa** [comment]
There is a inline_quoted.html.haml.  I just pulled today.

Boom! removed backend all is well, thank you!

**Comment by mojavelinux** [comment]
:+1:
